# Generated by Django 5.0.6 on 2024-06-19 07:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sensors", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sensorsdata",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 6, 19, 7, 22, 57, 994887, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
